---
- name: Test fetch
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: check for file
     win_stat: 
      path: C:\Ansible\test.txt
      
   - name: test fetch
     fetch: 
      src: C:/Ansible/test.txt
      dest: /home/localadmin/files/test.txt
      flat: yes
  
