---
- name: Test fetch
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: check for file
     win_stat: 
      path: C:\Ansible\test.txt
      
   - name: test fetch
     fetch: 
      src: 'C:/Ansible/test/test.txt'
      dest: "/tmp/test_{{ ansible_hostname }}"
      flat: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: '{{ ucet }}'
      ansible_become_pass: '{{ heslo }}'
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
