---
- name: Test fetch
  hosts: "{{ seznam_stanic }}"
  tasks: 
     
   -name: raw
    raw: Get-Service > C:/test.txt
      
   - name: test fetch
     fetch: 
      src: 'C:/test.txt'
      dest: "/tmp/test_{{ ansible_hostname }}"
      flat: yes
      fail_on_missing: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: '{{ ucet }}'
      ansible_become_pass: '{{ heslo }}'
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only

