---
- name: Vytvoří AnsibleAdmina
  hosts: "{{ seznam_stanic }}"
  tasks: 
  - name: Vytvoří AnsibleAdmina
    win_user: 
     name: AnsibleAdmin
     password: "{{ heslo }}"
     password_never_expires: true
     user_cannot_change_password: yes
     state: present
     groups: 
       - Administrators
