---
- name: Vytvoření stálého jedinečného přístupu do PC
  hosts: "{{ seznam_stanic}}"
  tasks: 
   - name: Vytvoří složku pro certifikát, pokud je potřeba
     win_file: 
      path: 'C:\Ansible\temp'
      state: directory
     
   - name: Generování a exportování certifikátu do C:\Ansible\temp
     win_shell: |
       Set-Item -Path WSMan:\localhost\Service\Auth\Certificate -Value $true
       $username = "LocalAdmin"
       $output_path = "C:\Ansible\temp"
       $cert = New-SelfSignedCertificate -Type Custom `
           -Subject "CN=$username" `
           -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.2","2.5.29.17={text}upn=$username@localhost") `
           -KeyUsage DigitalSignature,KeyEncipherment `
           -KeyAlgorithm RSA `
           -KeyLength 2048
       $pem_output = @()
       $pem_output += "-----BEGIN CERTIFICATE-----"
       $pem_output += [System.Convert]::ToBase64String($cert.RawData) -replace ".{64}", "$&`n"
       $pem_output += "-----END CERTIFICATE-----"
       [System.IO.File]::WriteAllLines("$output_path\cert.pem", $pem_output)
       [System.IO.File]::WriteAllBytes("$output_path\cert.pfx", $cert.Export("Pfx"))
       
   - name: Kopírování certu na Ansible server
     fetch: 
      src: 'C:\temp\cert.pem'
      dest: "/srv/cert/{{ ansible_hostname }}_pem"
      flat: yes
      
   - name: Kopírování klíče na Ansible server
     fetch: 
      src: 'C:\temp\cert.pfx'
      dest: "/srv/cert/{{ ansible_hostname }}_pfx"
      flat: yes
    
