---
- name: znehodnotí certifikát
  hosts: all
  tasks: 
   - name: Generování a exportování certifikátu do C:\temp
     win_shell: |
       Set-Item -Path WSMan:\localhost\Service\Auth\Certificate -Value $true
       $username = "AnsibleAdmin"
       $output_path = "C:\temp"
       $cert = New-SelfSignedCertificate -Type Custom `
           -Subject "CN=$username" `
           -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.2","2.5.29.17={text}upn=$username@localhost") `
           -KeyUsage DigitalSignature,KeyEncipherment `
           -KeyAlgorithm RSA `
           -KeyLength 2048 `
           -NotAfter (Get-Date).AddYears(9)
       $pem_output = @()
       $pem_output += "-----BEGIN CERTIFICATE-----"
       $pem_output += [System.Convert]::ToBase64String($cert.RawData) -replace ".{64}", "$&`n"
       $pem_output += "-----END CERTIFICATE-----"
       [System.IO.File]::WriteAllLines("$output_path\cert.pem", $pem_output)
       [System.IO.File]::WriteAllBytes("$output_path\cert.pfx", $cert.Export("Pfx"))
    
   - name: Konverze pfx do pem
     win_command: |
       "c:\Program Files\OpenSSL-Win64\bin\openssl.exe"
       pkcs12 -in C:\temp\cert.pfx -nocerts -nodes -out C:\temp\cert_key.pem -passin pass: -passout pass:
      
   - name: Import issuing certifikátu (certifikát autority) do Trusted root certificate authorities #je stejný, jako cert samotný, protože je SelfSigned
     win_shell: |
       $cert = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Certificate2
       $cert.Import("C:\temp\cert.pem")
       $store_name = [System.Security.Cryptography.X509Certificates.StoreName]::Root
       $store_location = [System.Security.Cryptography.X509Certificates.StoreLocation]::LocalMachine
       $store = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Store -ArgumentList $store_name, $store_location
       $store.Open("MaxAllowed")
       $store.Add($cert)
       $store.Close()
       
   - name: Import certifikátu do TrustedPeople
     win_shell: |
       $cert = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Certificate2
       $cert.Import("C:\temp\cert.pem")
       $store_name = [System.Security.Cryptography.X509Certificates.StoreName]::TrustedPeople
       $store_location = [System.Security.Cryptography.X509Certificates.StoreLocation]::LocalMachine
       $store = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Store -ArgumentList $store_name, $store_location
       $store.Open("MaxAllowed")
       $store.Add($cert)
       $store.Close()
       
      
