---
- name: test
  hosts: all
  tasks: 
   - name: Konverze pfx do pem
     win_command: |
       "c:\Program Files\OpenSSL-Win64\bin\openssl.exe"
       pkcs12 -in C:\temp\cert.pfx -nocerts -nodes -out C:\temp\cert_key.pem -passin pass: -passout pass:
